This notebook (and the slides from lecture 8) will help you go straight from training a model in Colab to deploying it in a webpage with TensorFlow.js - without having to leave the browser.

Configure this notebook to work with your GitHub account by populating these fields.

In [86]:
!pip install tensorflowjs
!pip install urllib

  Could not find a version that satisfies the requirement urllib (from versions: )
No matching distribution found for urllib


In [0]:
import urllib.request
from sklearn.model_selection import train_test_split

In [0]:
# your github username
USER_NAME = "ijupudy" 

# the email associated with your commits
# (may not matter if you leave it as this)
USER_EMAIL = "ikya07@gmail.com" 

# the user token you've created (see the lecture 8 slides for instructions)
TOKEN = "41bb2320445c3075b181fca23088343bbf86e32f" 

# site name
# for example, if my user_name is "foo", then this notebook will create
# a site at https://foo.github.io/hw4/
SITE_NAME = "hw4"

Next, run this cell to configure git.

In [0]:
!git config --global user.email {USER_NAME}
!git config --global user.name  {USER_EMAIL}

Clone your GitHub pages repo (see the lecture 8 slides for instructions on how to create one).

In [90]:
import os
repo_path = USER_NAME + '.github.io'
if not os.path.exists(os.path.join(os.getcwd(), repo_path)):
  !git clone https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io

Cloning into 'ijupudy.github.io'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 39 (delta 7), reused 36 (delta 7), pack-reused 0
Unpacking objects: 100% (39/39), done.


In [91]:
os.chdir(repo_path)
!git pull

Already up to date.


Create a folder for your site.

In [0]:
project_path = os.path.join(os.getcwd(), SITE_NAME)
if not os.path.exists(project_path): 
  os.mkdir(project_path)
os.chdir(project_path)

These paths will be used by the converter script.

In [0]:
# DO NOT MODIFY
MODEL_DIR = os.path.join(project_path, "model_js")
if not os.path.exists(MODEL_DIR):
  os.mkdir(MODEL_DIR)

As an example, we will create and vectorize a few documents. (Check out https://www.gutenberg.org/ for a bunch of free e-books.)

In [0]:
req = urllib.request.Request('https://www.gutenberg.org/files/58314/58314-0.txt')
with urllib.request.urlopen(req) as response:
  book1 = response.read()
book1 = book1.decode("utf-8") 
book1 = book1.split("\n")
book1_samp = book1[500:1600]

req = urllib.request.Request('https://www.gutenberg.org/files/58319/58319-0.txt')
with urllib.request.urlopen(req) as response:
  book2 = response.read()
book2 = book2.decode("utf-8") 
book2 = book2.split("\n")
book2_samp = book2[500:1600]

req = urllib.request.Request('https://www.gutenberg.org/files/58310/58310-0.txt')
with urllib.request.urlopen(req) as response:
  book3 = response.read()
book3 = book3.decode("utf-8") 
book3 = book3.split("\n")
book3_samp = book3[500:1600]

In [0]:
X = []
y = []
for line_book1 in book1_samp:
  X.append(line_book1)
  y.append(0)
for line_book2 in book2_samp:
  X.append(line_book2)
  y.append(1)
for line_book3 in book3_samp:
  X.append(line_book3)
  y.append(2)

In [0]:
X_train,X_test,y_train,y_test = train_test_split(X, y, random_state = 42, stratify = y )

In [0]:
import pandas as pd

In [98]:
pd.DataFrame(X_test,y_test)

0
2   unaccountable inconsistencies and self-contrad...
2   1175--only a few days before the treaty with R...
1   about 1540, Henry VIII. of England used for hi...
1                                                  \r
2   those of the royal household itself. Henry had...
1   and paper-mills sprang up as if by magic along...
0   As an evidence of their advanced civilization,...
2   later, when Raymond was recalled by Henry to E...
2   into Ireland and subdue it for him and his son...
0   slaveholders, which, however, had been previou...
2   Louis was only for Anjou and Maine, and he add...
0   well as under Hebrew dominion. Repeatedly did ...
0   for mixing with black chattels--but what penal...
0   but none of them were so crowded with slaves a...
0   baneful and destructive as is the organization...
0   an additional illustration of the eternal and ...
2   It set John in the foremost rank among the bar...
1   property of the United States was valued at $1...
0   Slavery, however, never became an integral ele...
0   were, and it is questionable if it can ever be...
0                                         parallel.\r
0                                                  \r
2   went with him; for when Philip attacked Berry ...
1                                                  \r
1   to collect rags for the paper-mills at Milton,...
1   sheet was repaired with paste. This work was s...
1   water runs clear and unsullied, a bleaching ma...
1   water is turned in at one end, the knife-roll ...
2            the legates on February 17 (1187).[97]\r
0   skin, or pigments mixed, which constituted the...
..                                                ...
2   [64] Cf. _Gesta Hen._ vol. i. pp. 172, 173; Gi...
2   in the year immediately preceding their transf...
1   the print of the watermark used is given in He...
0   chattelhood, among the primitive pastoral trib...
2   king, and so too, apparently, was a castle on ...
1               erection of the new mill at Dalton:\r
1   English mill, must have been the second, if no...
2   years elapsed before he set foot in his dioces...
2   but a half-hearted welcome;[82] and John did n...
2   that is written down here is Lord John, your s...
1   In anticipation of the coming conflict, New Yo...
2                  _Kingdom of Roderic_ {CONNAUGHT}\r
0   these once great cities had become tributary t...
2                                                  \r
1   introduced into France. At that time the Frenc...
2   the English Crown,[117] being at that very tim...
1   country, will direct their children or domesti...
0   malignant influence of domestic slavery. Slave...
1   The first mill to be established in the northe...
2   make king in Ireland whichever of his sons he ...
0   Accordingly Phoenician slaves became more and ...
1   the process of decomposition, the rags were of...
1   disagreeable to his olfactory nerves. Yet the ...
0   even in the primitive theocratic epochs of Ben...
0   went on uninterruptedly during the almost coun...
0   these various populations against the oligarch...
2   counsellors of Richard, as he had been of Henr...
1                                                  \r
1                                                  \r
2   to the count by his brother out of the exchequ...

[825 rows x 1 columns]

In [99]:
X_test

['unaccountable inconsistencies and self-contradictions, the seemingly\r',
 '1175--only a few days before the treaty with Roderic was signed--by\r',
 'about 1540, Henry VIII. of England used for his private correspondence,\r',
 '\r',
 'those of the royal household itself. Henry had had his seneschal, his\r',
 'and paper-mills sprang up as if by magic along all the swift-flowing\r',
 'As an evidence of their advanced civilization, it may be mentioned\r',
 'later, when Raymond was recalled by Henry to England on the death of\r',
 'into Ireland and subdue it for him and his son John, to whom he had\r',
 'slaveholders, which, however, had been previously appropriated by\r',
 'Louis was only for Anjou and Maine, and he adds: “In hac autem honorum\r',
 'well as under Hebrew dominion. Repeatedly did Egyptians, Assyrians\r',
 'for mixing with black chattels--but what penalty threatened the _white\r',
 'but none of them were so crowded with slaves as were Byblos, Tyre,\r',
 'baneful and destruc

Tokenize the documents, create a word index (word -> number).

In [0]:
max_len = 20
num_words = 1000
from keras.preprocessing.text import Tokenizer
# Fit the tokenizer on the training data
t = Tokenizer(num_words=num_words)
t.fit_on_texts(X_train)

In [101]:
print(t.word_index)

{'the': 1, 'of': 2, '\r': 3, 'and': 4, 'in': 5, 'to': 6, 'a': 7, 'was': 8, 'as': 9, 'that': 10, 'by': 11, 'it': 12, 'the\r': 13, 'for': 14, 'or': 15, 'his': 16, 'which': 17, 'were': 18, 'from': 19, 'paper': 20, 'is': 21, 'with': 22, 'at': 23, 'their': 24, 'had': 25, 'but': 26, 'on': 27, 'not': 28, 'this': 29, 'they': 30, 'be': 31, 'john': 32, 'been': 33, 'he': 34, 'and\r': 35, 'have': 36, 'of\r': 37, 'all': 38, 'vol': 39, 'p': 40, 'are': 41, '”': 42, 'into': 43, 'these': 44, 'an': 45, 'made': 46, 'who': 47, 'henry': 48, 'other': 49, 'slaves': 50, 'its': 51, 'one': 52, 'them': 53, 'so': 54, 'some': 55, 'him': 56, 'when': 57, 'first': 58, 'england': 59, 'slavery': 60, 'mill': 61, 'to\r': 62, 'such': 63, 'richard': 64, 'king': 65, 'in\r': 66, 'great': 67, 'only': 68, 'rags': 69, 'any': 70, 'i': 71, 'also': 72, 'de': 73, 'two': 74, 'same': 75, 'before': 76, 'phoenicians': 77, 'no': 78, 'year': 79, 'there': 80, 'a\r': 81, 'upon': 82, 'being': 83, 'new': 84, 'more': 85, 'was\r': 86, 'than': 

Here's how we vectorize a document.

In [102]:
vectorized = t.texts_to_sequences(X_train)
print(vectorized)

[[3], [4, 237, 5, 55, 154, 284, 5, 7, 642], [5, 426, 5, 643, 1, 2, 1], [30, 78, 879, 318, 1, 217, 879, 366, 19, 38], [644, 645, 367, 199, 646, 57, 30, 12, 95], [319, 1, 75, 5, 7, 155, 61, 112], [880, 2, 1, 156, 10, 21, 130, 647, 15, 368], [1, 14, 218, 46, 16, 67, 43, 7, 427, 37], [3], [881, 2, 512, 285, 24, 3], [12, 96, 33, 10, 5, 513, 184, 1, 219, 648, 89, 13], [649, 1, 185, 369, 1, 260, 4, 514, 2, 101, 47, 650], [171, 9, 90, 260, 117, 68, 11, 82, 1], [320, 118, 10, 34, 8, 6, 23, 238, 6, 101, 184, 261], [43, 428, 238, 85, 1, 220, 2, 515, 286], [3], [3], [5, 10, 882, 2, 1, 102, 17, 34, 38, 62], [84, 429, 5, 8, 28, 5, 54, 12, 21, 430, 3], [25, 78, 1, 2, 5, 1, 200, 5, 516, 86], [101, 42, 29, 287, 883, 21, 185, 6, 36, 651, 11, 7, 884, 3], [2, 426, 47, 5, 1, 370, 79], [2, 1, 288, 2, 285, 4, 24, 321, 3], [17, 41, 5, 7, 371, 157, 1, 42, 9, 322], [517, 1, 221, 119, 262], [431, 1, 2, 1, 58, 432, 885, 5, 84, 429, 120, 323], [22, 1, 20, 186, 21, 158, 5, 1, 886], [3], [1, 17, 1, 201, 25, 19, 44, 

Apply padding if necessary.

In [0]:
from keras.preprocessing.sequence import pad_sequences
padded = pad_sequences(vectorized, maxlen=max_len, padding='post')

In [104]:
print(padded.shape)

(2475, 20)


We will save the word index in metadata. Later, we'll use it to convert words typed in the browser to numbers for prediction.

In [0]:
metadata = {
  'word_index': t.word_index,
  'max_len': max_len,
  'vocabulary_size': num_words,
}

Define a model.

In [106]:
embedding_size = 8
n_classes = 3
epochs = 10

import keras
model = keras.Sequential()
model.add(keras.layers.Embedding(num_words, embedding_size, input_shape=(max_len,)))
model.add(keras.layers.LSTM(16))
model.add(keras.layers.Dense(3, activation='softmax'))
model.compile('adam', 'sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 20, 8)             8000      
_________________________________________________________________
lstm_4 (LSTM)                (None, 16)                1600      
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 51        
Total params: 9,651
Trainable params: 9,651
Non-trainable params: 0
_________________________________________________________________


Prepare some training data.

In [107]:
X_train = t.texts_to_sequences(X_train)
X_train = pad_sequences(X_train, maxlen=max_len, padding='post')
print(X_train)

[[  3   0   0 ...   0   0   0]
 [  4 237   5 ...   0   0   0]
 [  5 426   5 ...   0   0   0]
 ...
 [  1 220   2 ...   0   0   0]
 [134  44 158 ...   0   0   0]
 [  3   0   0 ...   0   0   0]]


In [108]:
model.fit(X_train, y_train, epochs=epochs, validation_split = 0.3)

Train on 1732 samples, validate on 743 samples
Epoch 1/10
1732/1732 [==============================] - 2s 1ms/step - loss: 1.0988 - acc: 0.3297 - val_loss: 1.0985 - val_acc: 0.3122
Epoch 2/10
1732/1732 [==============================] - 1s 478us/step - loss: 1.0433 - acc: 0.4682 - val_loss: 0.9096 - val_acc: 0.5289
Epoch 3/10
1732/1732 [==============================] - 1s 474us/step - loss: 0.7948 - acc: 0.5739 - val_loss: 0.7879 - val_acc: 0.5760
Epoch 4/10
1732/1732 [==============================] - 1s 470us/step - loss: 0.7130 - acc: 0.6068 - val_loss: 0.8077 - val_acc: 0.5532
Epoch 5/10
1732/1732 [==============================] - 1s 479us/step - loss: 0.6659 - acc: 0.6536 - val_loss: 0.7534 - val_acc: 0.6124
Epoch 6/10
1732/1732 [==============================] - 1s 485us/step - loss: 0.6137 - acc: 0.6848 - val_loss: 0.7620 - val_acc: 0.6245
Epoch 7/10
1732/1732 [==============================] - 1s 494us/step - loss: 0.5698 - acc: 0.7546 - val_loss: 0.7773 - val_acc: 0.6420
Epo

Demo using the model to make predictions.

In [109]:
x_test = t.texts_to_sequences(X_test)
x_test = pad_sequences(x_test, maxlen=max_len, padding='post')
print(x_test)

[[  4   1   0 ...   0   0   0]
 [ 68   7 765 ...   0   0   0]
 [109  48   2 ...   0   0   0]
 ...
 [  3   0   0 ...   0   0   0]
 [  3   0   0 ...   0   0   0]
 [  6   1 346 ...   0   0   0]]


In [110]:
preds = model.predict(x_test)
print(preds)
import numpy as np
print(np.argmax(preds))

[[0.24120954 0.73644716 0.02234332]
 [0.02220856 0.01492796 0.96286345]
 [0.00682821 0.00465389 0.9885179 ]
 ...
 [0.2161912  0.48145914 0.3023497 ]
 [0.2161912  0.48145914 0.3023497 ]
 [0.00816101 0.0052709  0.9865681 ]]
2387


In [111]:
model.evaluate(x_test,y_test)

825/825 [==============================] - 0s 98us/step


[0.8943945200515516, 0.6472727281397039]

Convert the model

In [112]:
import json
import tensorflowjs as tfjs

metadata_json_path = os.path.join(MODEL_DIR, 'metadata.json')
json.dump(metadata, open(metadata_json_path, 'wt'))
tfjs.converters.save_keras_model(model, MODEL_DIR)
print('\nSaved model artifcats in directory: %s' % MODEL_DIR)


Saved model artifcats in directory: /content/ijupudy.github.io/hw4/ijupudy.github.io/hw4/ijupudy.github.io/hw4/model_js


Write an index.html and an index.js file configured to load our model.

In [0]:
index_html = """
<!doctype html>

<body>
  <style>
    #textfield {
      font-size: 120%;
      width: 60%;
      height: 200px;
    }
  </style>
  <h1>
    Title
  </h1>
  <hr>
  <div class="create-model">
    <button id="load-model" style="display:none">Load model</button>
  </div>
  <div>
    <div>
      <span>Vocabulary size: </span>
      <span id="vocabularySize"></span>
    </div>
    <div>
      <span>Max length: </span>
      <span id="maxLen"></span>
    </div>
  </div>
  <hr>
  <div>
    <select id="example-select" class="form-control">
      <option value="example1">Slavery in History</option>
      <option value="example2">The Story of Paper-making</option>
      <option value="example3">John Lackland</option>
    </select>
  </div>
  <div>
    <textarea id="text-entry"></textarea>
  </div>
  <hr>
  <div>
    <span id="status">Standing by.</span>
  </div>

  <script src='https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js'></script>
  <script src='index.js'></script>
</body>
"""

In [0]:
index_js = """
const HOSTED_URLS = {
  model:
      'model_js/model.json',
  metadata:
      'model_js/metadata.json'
};

const examples = {
  'example1':
      'Natives of Asia were sold became something more than a name.',
  'example2':
      'This work was so neatly and deftly water runs clear and unsullied, a bleaching material is put into the water is turned in at one end, the knife-roll having been adjusted so the legates on February 17 (1187)',
  'example3':
      'Their central situation for the commerce of the known and the castles of Tickhill and Nottingham to John.'      
};

function status(statusText) {
  console.log(statusText);
  document.getElementById('status').textContent = statusText;
}

function showMetadata(metadataJSON) {
  document.getElementById('vocabularySize').textContent =
      metadataJSON['vocabulary_size'];
  document.getElementById('maxLen').textContent =
      metadataJSON['max_len'];
}

function settextField(text, predict) {
  const textField = document.getElementById('text-entry');
  textField.value = text;
  doPredict(predict);
}

function setPredictFunction(predict) {
  const textField = document.getElementById('text-entry');
  textField.addEventListener('input', () => doPredict(predict));
}

function disableLoadModelButtons() {
  document.getElementById('load-model').style.display = 'none';
}

function doPredict(predict) {
  const textField = document.getElementById('text-entry');
  const result = predict(textField.value);
  score_string = "Class scores: ";
  for (var x in result.score) {
    score_string += x + " ->  " + result.score[x].toFixed(3) + ", "
  }
  //console.log(score_string);
  status(
      score_string + ' elapsed: ' + result.elapsed.toFixed(3) + ' ms)');
}

function prepUI(predict) {
  setPredictFunction(predict);
  const testExampleSelect = document.getElementById('example-select');
  testExampleSelect.addEventListener('change', () => {
    settextField(examples[testExampleSelect.value], predict);
  });
  settextField(examples['example1'], predict);
}

async function urlExists(url) {
  status('Testing url ' + url);
  try {
    const response = await fetch(url, {method: 'HEAD'});
    return response.ok;
  } catch (err) {
    return false;
  }
}

async function loadHostedPretrainedModel(url) {
  status('Loading pretrained model from ' + url);
  try {
    const model = await tf.loadModel(url);
    status('Done loading pretrained model.');
    disableLoadModelButtons();
    return model;
  } catch (err) {
    console.error(err);
    status('Loading pretrained model failed.');
  }
}

async function loadHostedMetadata(url) {
  status('Loading metadata from ' + url);
  try {
    const metadataJson = await fetch(url);
    const metadata = await metadataJson.json();
    status('Done loading metadata.');
    return metadata;
  } catch (err) {
    console.error(err);
    status('Loading metadata failed.');
  }
}

class Classifier {

  async init(urls) {
    this.urls = urls;
    this.model = await loadHostedPretrainedModel(urls.model);
    await this.loadMetadata();
    return this;
  }

  async loadMetadata() {
    const metadata =
        await loadHostedMetadata(this.urls.metadata);
    showMetadata(metadata);
    this.maxLen = metadata['max_len'];
    console.log('maxLen = ' + this.maxLen);
    this.wordIndex = metadata['word_index']
  }

  predict(text) {
    // Convert to lower case and remove all punctuations.
    const inputText =
        text.trim().toLowerCase().replace(/(\.|\,|\!)/g, '').split(' ');
    // Look up word indices.
    const inputBuffer = tf.buffer([1, this.maxLen], 'float32');
    for (let i = 0; i < inputText.length; ++i) {
      const word = inputText[i];
      inputBuffer.set(this.wordIndex[word], 0, i);
      //console.log(word, this.wordIndex[word], inputBuffer);
    }
    const input = inputBuffer.toTensor();
    //console.log(input);

    status('Running inference');
    const beginMs = performance.now();
    const predictOut = this.model.predict(input);
    //console.log(predictOut.dataSync());
    const score = predictOut.dataSync();//[0];
    predictOut.dispose();
    const endMs = performance.now();

    return {score: score, elapsed: (endMs - beginMs)};
  }
};

async function setup() {
  if (await urlExists(HOSTED_URLS.model)) {
    status('Model available: ' + HOSTED_URLS.model);
    const button = document.getElementById('load-model');
    button.addEventListener('click', async () => {
      const predictor = await new Classifier().init(HOSTED_URLS);
      prepUI(x => predictor.predict(x));
    });
    button.style.display = 'inline-block';
  }

  status('Standing by.');
}

setup();
"""

In [0]:
with open('index.html','w') as f:
  f.write(index_html)
  
with open('index.js','w') as f:
  f.write(index_js)

In [116]:
!ls

index.html  index.js  model_js


Commit and push everything. Note: we're storing large binary files in GitHub, this isn't ideal (if you want to deploy a model down the road, better to host it in a cloud storage bucket).

In [117]:
!git add . 
!git commit -m "colab -> github"
!git push https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io/ master

[master 8bd1ae2] colab -> github
 3 files changed, 4 insertions(+), 4 deletions(-)
 rewrite hw4/model_js/group1-shard1of1 (99%)
Counting objects: 7, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 35.85 KiB | 17.92 MiB/s, done.
Total 7 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/ijupudy/ijupudy.github.io/
   302bcab..8bd1ae2  master -> master


All done! Hopefully everything worked. You may need to wait a few moments for the changes to appear in your site. If not working, check the JavaScript console for errors (in Chrome: View -> Developer -> JavaScript Console).

In [118]:
print("Now, visit https://%s.github.io/%s/index.html" % (USER_NAME, SITE_NAME))

Now, visit https://ijupudy.github.io/hw4/index.html


If you are debugging and Chrome is failing to pick up your changes, though you've verified they're present in your GitHub repo, see the second answer to: https://superuser.com/questions/89809/how-to-force-refresh-without-cache-in-google-chrome